//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace WingtipToysForFireBird3;

interface

type
  Site = public partial class
  protected 
    var htmlControl: System.Web.UI.HtmlControls.HtmlElement;
    var adminLink: System.Web.UI.HtmlControls.HtmlAnchor;
    var cartCount: System.Web.UI.HtmlControls.HtmlAnchor;
    var Image1: System.Web.UI.WebControls.Image;
    var CategoryMenu: WingtipToysForFireBird3.Components.Controls.MenuCategory;
    var MainContent: System.Web.UI.WebControls.ContentPlaceHolder;
  end;
  
implementation

end.
